export const SKILLS_LIST = [
  'Programming (React Native)',
  'Programming (Python)',
  'Programming (JavaScript)',
  'Graphic Design',
  'UI/UX Design',
  'Content Writing',
  'Digital Marketing',
  'Video Editing',
  'Photography',
  'Public Speaking',
  'Project Management',
  'Data Science',
  'Machine Learning',
  'Cybersecurity',
  'Blogging',
  'SEO / SEM',
  'Social Media Management',
  'Copywriting',
  'Illustration',
  'Motion Graphics',
  '3D Modeling',
  'Music Production',
  'Singing',
  'Guitar / Piano',
  'French Language',
  'Spanish Language',
  'German Language',
  'Cooking',
  'Yoga',
  'Fitness Training',
  'Financial Planning',
  'Investing',
  'Public Relations',
  'Event Planning',
  'Legal Advice',
  'Soft Skills',
  'Chess',
];
